// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4N-xSEh_FzGGGQi-n-eFFu_1Si05VJLE',
    appId: '1:632617035885:web:ad42ca2a0260f5c599f764',
    messagingSenderId: '632617035885',
    projectId: 'daftartugas-7fcef',
    authDomain: 'daftartugas-7fcef.firebaseapp.com',
    databaseURL: 'https://daftartugas-7fcef-default-rtdb.firebaseio.com',
    storageBucket: 'daftartugas-7fcef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQo-pI93HHoY5CgmcvCmHMxKJjpC7qv_k',
    appId: '1:632617035885:android:e17572f3ccce833899f764',
    messagingSenderId: '632617035885',
    projectId: 'daftartugas-7fcef',
    databaseURL: 'https://daftartugas-7fcef-default-rtdb.firebaseio.com',
    storageBucket: 'daftartugas-7fcef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlLnJ8Gk9Injg4ThJriYyeMffQVMhL2ys',
    appId: '1:632617035885:ios:fc6b064cde70942c99f764',
    messagingSenderId: '632617035885',
    projectId: 'daftartugas-7fcef',
    databaseURL: 'https://daftartugas-7fcef-default-rtdb.firebaseio.com',
    storageBucket: 'daftartugas-7fcef.firebasestorage.app',
    iosBundleId: 'com.example.tugasfire4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlLnJ8Gk9Injg4ThJriYyeMffQVMhL2ys',
    appId: '1:632617035885:ios:fc6b064cde70942c99f764',
    messagingSenderId: '632617035885',
    projectId: 'daftartugas-7fcef',
    databaseURL: 'https://daftartugas-7fcef-default-rtdb.firebaseio.com',
    storageBucket: 'daftartugas-7fcef.firebasestorage.app',
    iosBundleId: 'com.example.tugasfire4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4N-xSEh_FzGGGQi-n-eFFu_1Si05VJLE',
    appId: '1:632617035885:web:ec46bd59ec8b37c499f764',
    messagingSenderId: '632617035885',
    projectId: 'daftartugas-7fcef',
    authDomain: 'daftartugas-7fcef.firebaseapp.com',
    databaseURL: 'https://daftartugas-7fcef-default-rtdb.firebaseio.com',
    storageBucket: 'daftartugas-7fcef.firebasestorage.app',
  );
}
